[project]
name = "A1"
version = "0.1.0"
dependencies = [
    "umap-learn",
    "scipy",
    "scikit-learn",
    "sentence-transformers",
    "matplotlib",
    "pyvis",
    "numpy",
    "seaborn",
    "branca",
    "pandas",
    "numba>=0.56.4"  # Ensure a compatible version
]
